---
title: "Comparison of liger with mhg"
author: "Jean Fan"
date: '`r Sys.Date()`'
output: html_document
vignette: |
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Vignette Title} \usepackage[utf8]{inputenc}
---

```{r, include = FALSE}
library(knitr)
opts_chunk$set(
    warning = FALSE,
    message = FALSE,
    fig.show = 'hold',
    fig.path = 'figures/comparison-',
    cache.path = 'cache/comparison-',
    cache = TRUE
)
```

```{r, simulate}
library(liger)
library(mhg)

# Simulate

library(liger)
# load gene set
data("org.Hs.GO2Symbol.list")  
# get universe
universe <- unique(unlist(org.Hs.GO2Symbol.list))
# get a gene set
gs <- org.Hs.GO2Symbol.list[[1]]
# fake dummy example where everything in gene set is perfectly enriched
vals <- rnorm(length(universe), 0, 10)
names(vals) <- universe
vals[gs] <- rnorm(length(gs), 100, 10)
# add some noise
vals[sample(1:length(universe), 1000)] <-  rnorm(1000, 100, 10)
# test previously perfectly enriched gene set again
gs <- org.Hs.GO2Symbol.list[[1]]
```

```{r, liger}
# Run liger
liger1 <- gsea(values=vals, geneset=gs)
liger2 <- gsea(values=vals, geneset=gs, rank=TRUE)
```

```{r, mhg}
# Wrapper for mhg
mhgsea <- function(values, geneset) {
  # Fold change
  fc <- sort(values, decreasing=TRUE)
  # Size of the population.
  N <- length(values)
  # Successes in the population.
  K <- sum(geneset %in% names(values))
  # Only consider enrichments in the first L observations.
  L <- N
  # Require at least X successes in the first L observations.
  X <- 1
  # Define items in the population as successes.
  x <- as.numeric(names(fc) %in% geneset)
  # Test for enrichment.
  res <- mhg_test(x, N, K, L, X)
  # This is how you can plot the results.
  plot_mhg(
    values = fc,
    x = x,
    res = res,
    n = L,
    value = bquote("values")
  )
  return(res)
}

# Run mhg
res <- mhgsea(values=vals, geneset=gs)
```