// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gseaRandCore
Rcpp::List gseaRandCore(arma::vec sset, arma::vec eso, int nsamples);
RcppExport SEXP _liger_gseaRandCore(SEXP ssetSEXP, SEXP esoSEXP, SEXP nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type sset(ssetSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eso(esoSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(gseaRandCore(sset, eso, nsamples));
    return rcpp_result_gen;
END_RCPP
}
// gseaBulkCore
Rcpp::List gseaBulkCore(arma::mat setm, arma::vec eso, int nsamples);
RcppExport SEXP _liger_gseaBulkCore(SEXP setmSEXP, SEXP esoSEXP, SEXP nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type setm(setmSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eso(esoSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(gseaBulkCore(setm, eso, nsamples));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_liger_gseaRandCore", (DL_FUNC) &_liger_gseaRandCore, 3},
    {"_liger_gseaBulkCore", (DL_FUNC) &_liger_gseaBulkCore, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_liger(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
