# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gseaRandCore <- function(sset, eso, nsamples, seed) {
    .Call('_liger_gseaRandCore', PACKAGE = 'liger', sset, eso, nsamples, seed)
}

gseaBulkCore <- function(setm, eso, nsamples, seed) {
    .Call('_liger_gseaBulkCore', PACKAGE = 'liger', setm, eso, nsamples, seed)
}

